### ISSUE TITLE
Turn project into a library

### ISSUE THREAD

**Issue by LeonardoVal** [chacaa/CSS2SASS#1]
Currently the `index.js` uses other files included in the repo. This is not good if the project is going to be used as a library. All the code should be in one JS file to be required.
A good way to do this without bundling all the code is to concatenate the source files using a build tool like [Grunt](https://gruntjs.com/) or [Gulp](https://gulpjs.com/). These tools can also minify the code also. You would like to separate files into: a `src/` folder for the original JS source, `build/` or `dist/` for the generated files, and `test/` or `tests/` for the test cases. Test cases can integrated in the build process using tools like [Mocha](https://mochajs.org/).

**Comment by chacaa** [comment]
I did that, later i'll take a look at those tools. Thanks!
