### ISSUE TITLE
String format function in `utils/errorManager.js`

### ISSUE THREAD

**Issue by LeonardoVal** [chacaa/CSS2SASS#5]
Extending native JS types' prototypes is [not a good practice](https://stackoverflow.com/questions/14034180/why-is-extending-native-objects-a-bad-practice#14034242). Nonetheless, NodeJS has this functionality available: [utils.format](https://nodejs.org/api/util.html#util_util_format_format_args).

**Comment by chacaa** [comment]
In the upcoming commit the errors are going to be handled in a different way, so this fix isn't necessary  anymore. Anyways thanks for the tip!
